/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright 2019 IBM Corp.
 */

#ifndef __CONFIG_H
#define __CONFIG_H

#define CONFIG_CMDLINE_TAG
#define CONFIG_SETUP_MEMORY_TAGS
#define CONFIG_INITRD_TAG

#define CONFIG_SYS_SDRAM_BASE		0x80000000

#define AST2600_SRAM_BASE		0x10000000
#define AST2600_SRAM_SIZE		(64 * 1024)

#define CONFIG_SYS_INIT_RAM_ADDR        AST2600_SRAM_BASE
#define CONFIG_SYS_INIT_RAM_SIZE        AST2600_SRAM_SIZE

#define CONFIG_SYS_INIT_SP_ADDR \
        (CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)

#define CONFIG_SYS_MALLOC_LEN		(32 << 20)

#define CONFIG_BOOTCOMMAND		"bootm 20100000"
#define CONFIG_SYS_LOAD_ADDR		0x83000000
#define CONFIG_ENV_OVERWRITE

#endif	/* __CONFIG_H */
