#
# Copyright 2015 IBM Corp.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	=  timer.o reset.o mactest.o DRAM_SPI.o IO.o LIB.o MAC.o NCSI.o \
	PCI_SPI.o PHY.o SPIM.o STDUBOOT.o PLLTESTU.o TRAPTEST.o STRESS.o

obj-y	+= spl.o
